fare/file_management/views.py
"""Views for file_management of records."""

from __future__ import absolute_import, print_function

from flask import Blueprint, abort, current_app, redirect, render_template, \
    request, url_for
from flask_babelex import gettext as _
from flask_login import login_required
from flask_menu import register_menu
from flask_security import current_user, roles_accepted
from invenio_files_rest.models import Bucket, ObjectVersion
from sqlalchemy.orm.exc import NoResultFound

from .api import RecordFare
from .forms import RecordForm
from .search import StatusSearch
from .utils import get_all_arguments, get_all_education_levels, \
    get_all_subjects

# define a new Flask Blueprint that is register
# under the url path /file_management
blueprint = Blueprint(
    'file_management',
    __name__,
    url_prefix='/file_management',
    template_folder='templates',
    static_folder='static',
)


@blueprint.route('/user_uploads', methods=('GET',))
@login_required
@register_menu(blueprint, 'settings.status',
               _('%(icon)s Stato files',
                 icon='<i class="fa fa-check-circle fa-fw"></i>'
                 ),
               order=6
               )
def user_uploads():
    """View to let user see the status (revisioned=true/false) of his files."""
    status = StatusSearch()
    return render_template('file_management/user_uploads.html',
                           records_list=status.execute().hits)


@blueprint.route('/arguments', methods=('GET',))
def retrieve_arguments():
    """View to get all the arguments."""
    return get_all_arguments()


@blueprint.route('/search_page', methods=('GET',))
def search_page():
    """View to display the search page."""
    return render_template('file_management/search_page.html')


@blueprint.route('/guide_search', methods=('GET',))
def retrieve_guide_search():
    """View to display the guide to search records."""
    subjects = get_all_subjects()
    education_levels = get_all_education_levels()
    return render_template('file_management/guide_search.html',
                           subjects=subjects,
                           education_levels=education_levels)


@blueprint.route('/guide_permissions', methods=('GET',))
def retrieve_guide_permissions():
    """View to display the guide that explains the user roles."""
    return render_template('file_management/guide_permissions.html')


@blueprint.route('/guide_upload', methods=('GET',))
def retrieve_guide_upload():
    """View to display the guide to upload a record."""
    return render_template('file_management/guide_upload.html')


@blueprint.route('/create', methods=('GET', 'POST'))
@register_menu(blueprint, 'settings.createfile',
               _('%(icon)s Carica file',
                 icon='<i class="fa fa-file-text fa-fw"></i>'
                 ),
               order=5
               )
def create():
    """The create view."""
    if not current_user.is_authenticated:
        return render_template('file_management/info_create.html')

    form = RecordForm()
    # if the form is submitted and valid
    if form.validate_on_submit():
        list_names = form.contributor_name.data.split(",")
        list_contributors = []

        for contributor in list_names:
            t = {"name": contributor}
            list_contributors.append(t)

        # we creare contributors object with the submitted names
        contributors = list_contributors
        # set the owner as the current logged in user
        owner = int(current_user.get_id())
        # set the school order
        educationLevel = form.educationLevel.data
        # set the discipline
        subject = form.subject.data
        # set the argument
        coverage = form.coverage.data
        # set the license
        license = form.license.data
        # set the description
        description = form.description.data
        # set the file of the record
        content = form.file_content.data
        # create the record and set the revisioned field to false
        RecordFare.create_record(
          dict(
            title=form.title.data,
            contributors=contributors,
            owner=owner,
            educationLevel=educationLevel,
            subject=subject,
            coverage=coverage,
            license=license,
            description=description,
            revisioned=False,
          ),
          content
        )
        # redirect to the success page
        return redirect(url_for('file_management.success'))
    return render_template('file_management/create.html', form=form)


@blueprint.route('/revision/', methods=('GET',))
@login_required
@roles_accepted('admin', 'staff')
@register_menu(blueprint, 'settings.revision',
               _('%(icon)s Revisione contenuti',
                   icon='<i class="fa fa-eye fa-fw"></i>'),
               order=6,
               visible_when=lambda: bool(current_user.has_role('admin') or
                                         current_user.has_role('staff')
                                         ) is not False
               )
def revision_list():
    """View to display all unrevisioned records."""
    return render_template('file_management/unrevisioned.html')


@blueprint.route('/publish/', methods=('GET', 'POST'))
@login_required
def publish():
    """View to publish a record."""
    record_id = request.form['record_id']

    # retrieve the record
    try:
        record = RecordFare.get_record(record_id)
    except NoResultFound:

        current_app.logger.error(
                            "Impossible to publish file requested by user= " +
                            current_user.email + " ,record id not found: " +
                            record_id
                                )
        abort(404)

    RecordFare.publish_record(record)

    return render_template('file_management/unrevisioned.html')


@blueprint.route('/delete/', methods=('GET', 'POST'))
@login_required
def delete():
    """The delete view."""
    bucket_uuid = request.form['record_bucket']
    record_id = request.form['record_id']

    # get Bucket object
    bucket = Bucket.get(bucket_uuid)

    # chekc if the bucket exist
    if bucket is None:
        current_app.logger.error(
                        "Impossible to delete the file requested by user= " +
                        current_user.email + ", bucket not found: " +
                        bucket_uuid
        )
        abort(404)

    # store buckets values: version_id and the key
    values = str(bucket.objects[0]).split(':')
    version_id = values[1]
    key = values[2]
    # retrieve the fileinstance_id
    fileinstance_id = str(ObjectVersion.get(bucket, key, version_id).file_id)

    # creating MyRecord object, extention of invenio_records_files.Record
    try:
        record = RecordFare.get_record(record_id)
    except NoResultFound:

        current_app.logger.error(
                            "Impossible to delete file requested by user= " +
                            current_user.email + " ,record id not found: " +
                            record_id
                                )
        abort(404)

    # check if the user is the owner of the record or if is admin or staff
    if(
            (not current_user.id == record['owner']) and
            (not current_user.has_role('admin')) and
            (not current_user.has_role('staff'))
    ):
        current_app.logger.error(
                            "Impossible to delete file requested by user= " +
                            current_user.email + " , this user does not have \
                            the permission, action not allowed"
                                )
        abort(403)

    record.delete_record(fileinstance_id, record_id)
    return redirect(url_for('file_management.success_delete'))


@blueprint.route('/download/', methods=('GET', 'POST'))
def download():
    """The download view."""
    # storing the bucket uuid
    bucket_uuid = request.form['record_bucket']
    record_id = request.form['record_id']

    # check if the session is anonymous or not
    if not hasattr(current_user, 'email'):
        usr = "anonymous"
    else:
        usr = current_user.email

    # get Bucket object
    bucket = Bucket.get(bucket_uuid)

    # chekc if the bucket exist
    if bucket is None:
        current_app.logger.error(
                            "Impossible to download file requested by user= " +
                            usr + ", bucket not found: " + bucket_uuid
                                )
        abort(404)

    # store buckets values: bucket, version_id and the key
    values = str(bucket.objects[0]).split(':')
    bucket = values[0]
    version_id = values[1]
    key = values[2]

    try:
        record = RecordFare.get_record(record_id)
    except NoResultFound:

        current_app.logger.error(
                            "Impossible to download file requested by user= " +
                            usr + " ,record id not found: " + record_id
                                )
        abort(404)

    # check if the file is revisioned, if not only
    # staff member can download it to do the review
    if not record['revisioned']:
        if (
            (not current_user.has_role('admin')) and
            (not current_user.has_role('staff'))
        ):

            current_app.logger.error(
                            "Impossible to download file= " + record['title'] +
                            ", user= " + usr + " not authorized"
                                    )

            # forbidden for the user
            abort(403)

    return RecordFare.download_record(record, bucket, key, version_id, usr)


@blueprint.route("/success")
@login_required
def success():
    """The success view."""
    return render_template('file_management/success.html')


@blueprint.route("/success_delete")
@login_required
def success_delete():
    """The success view."""
    return render_template('file_management/success_delete.html')

fare/file_management/templates/file_management/advanced_search.html
{%- extends config.BASE_TEMPLATE %}

{% macro errors(field) %}
  {% if field.errors %}
  <span class="help-block">
    <ul class=errors>
    {% for error in field.errors %}
      <li>{{ error }}</li>
    {% endfor %}
    </ul>
  {% endif %}
  </span>
{% endmacro %}

{% block page_body %}
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h1 class="text-center">Ricerca avanzata</h1><br>
        <h4 class="text-center">
          Qui potrai selezionare i campi nel dettaglio per trovare risultati conformi alle tue esigenze
        </h4>
      </div>
      <div class="col-md-offset-3 col-md-6 well">
        <form action="{{ url_for('file_management.advanced_search') }}" method="POST" enctype="multipart/form-data">
            <div class="form-group {{ 'has-error' if form.title.errors }}">
              <label for="title">Titolo</label>
              {{ form.title(class_="form-control")|safe }}
              {{ errors(form.title) }}
            </div>
            <div class="form-group {{ 'has-error' if form.contributor_name.errors }}">
              <label for="contributor_name">Autore/i</label>
              <small>(separa gli autori con una virgola)</small>
              {{ form.contributor_name(class_="form-control")|safe }}
              {{ errors(form.contributor_name) }}
            </div>
            <div class="form-group {{ 'has-error' if form.educationLevel.errors }}">
              <label for="educationLevel">Ordine di scuola</label>
              {{ form.educationLevel(class_="form-control")|safe }}
              {{ errors(form.educationLevel) }}
            </div>
            <div class="form-group {{ 'has-error' if form.subject.errors }}">
              <label for="subject">Disciplina</label>
              {{ form.subject(class_="form-control")|safe }}
              {{ errors(form.subject) }}
            </div>
            <div class="form-group {{ 'has-error' if form.coverage.errors }}">
              <label for="coverage">Argomento</label>
              {{ form.coverage(class_="form-control")|safe }}
              {{ errors(form.coverage) }}
            </div>
            {{ form.csrf_token }}
            {{ errors(form.csrf_token) }}
            <button type="submit" class="btn btn-default">Cerca</button>
        </form>
      </div>
    </div>
  </div>

  {{ webpack['fare-advanced-search-argument.js'] }}

{% endblock page_body %}

fare/file_management/templates/file_management/create.html
{%- extends config.BASE_TEMPLATE %}

{% macro errors(field) %}
  {% if field.errors %}
  <span class="help-block">
    <ul class=errors>
    {% for error in field.errors %}
      <li>{{ error }}</li>
    {% endfor %}
    </ul>
  {% endif %}
  </span>
{% endmacro %}

{% block page_body %}
  <div class="container">

    <div class="element-block">

      <div class="row">

        <div class="col-md-12">
          <h1 class="text-center">Carica file</h1><br>
        </div>

      </div>

      <div class="row">

        <div class="col-md-3"></div>

        <div class="col-md-6 well">
          <form action="{{ url_for('file_management.create') }}" method="POST" enctype="multipart/form-data">
              <div class="form-group {{ 'has-error' if form.title.errors }}">
                <label for="title">Titolo</label>
                {{ form.title(class_="form-control")|safe }}
                {{ errors(form.title) }}
              </div>
              <div class="form-group {{ 'has-error' if form.contributor_name.errors }}">
                <label for="contributor_name">Autore/i</label>
                <small>(separa gli autori con una virgola)</small>
                {{ form.contributor_name(class_="form-control")|safe }}
                {{ errors(form.contributor_name) }}
              </div>
              <div class="form-group {{ 'has-error' if form.educationLevel.errors }}">
                <label for="educationLevel">Ordine di scuola</label>
                {{ form.educationLevel(class_="form-control")|safe }}
                {{ errors(form.educationLevel) }}
              </div>
              <div class="form-group {{ 'has-error' if form.subject.errors }}">
                <label for="subject">Disciplina</label>
                <small>
                  (Manca una disciplina? contattaci
                  <a href="https://openeducation.polito.it/it/contatti">qui <i class="fa fa-external-link" aria-hidden="true"></i></a>
                )
                </small>
                {{ form.subject(class_="form-control")|safe }}
                {{ errors(form.subject) }}
              </div>
              <div class="form-group {{ 'has-error' if form.coverage.errors }}">
                <label for="coverage">Argomento</label>
                <small>
                  (Manca un argomento? contattaci
                  <a href="https://openeducation.polito.it/it/contatti">qui <i class="fa fa-external-link" aria-hidden="true"></i></a>
                )
                </small>
                {{ form.coverage(class_="form-control")|safe }}
                {{ errors(form.coverage) }}
              </div>
              <div class="form-group {{ 'has-error' if form.license.errors }}">
                <label for="license">Licenza</label>
                <small>
                  (Per saperne di più sulle licenze Creative Commons clicca
                  <a href="https://creativecommons.org/licenses/?lang=it">qui <i class="fa fa-external-link" aria-hidden="true"></i></a>
                  )
                </small>
                {{ form.license(class_="form-control")|safe }}
                {{ errors(form.license) }}
              </div>
              <div class="form-group {{ 'has-error' if form.description.errors }}">
                <label for="description">Descrizione</label>
                {{ form.description(class_="form-control")|safe }}
                {{ errors(form.description) }}
              </div>
              <div class="form-group {{ 'has-error' if form.file_content.errors }}">
                <label for="file_content">File</label>
                {{ form.file_content(class_="form-control")|safe }}
                {{ errors(form.file_content) }}
              </div>
              {{ form.csrf_token }}
              {{ errors(form.csrf_token) }}
              <button type="submit" class="btn btn-default">Crea</button>
          </form>
        </div>

        <div class="col-md-3"></div>

      </div>

    </div>

  </div>

  {{ webpack['fare-argument.js'] }}

{% endblock page_body %}

fare/file_management/templates/file_management/guide_permissions.html
{%- extends config.BASE_TEMPLATE %}

{% block page_body %}

<div class="container">

  <h1 class="text-center">Guida ai permessi utente su FARE</h1>

  <p>
    Su FARE ci sono cinque tipi di uenti:
  </p>

  <ul>
    <li><b>Utente anonimo</b> può accedere ai contenuti del sito, scaricare i materiali </li>
    <li><b>Utente iscritto</b> può accedere ai contenuti del sito, scaricare i materiali, può caricare i materiali </li>
    <li><b>Utente staff</b> può accedere ai contenuti del sito, scaricare i materiali, può caricare i materiali, può avviare una videoconferenza, verifica e pubblica i materiali </li>
    <li><b>Utente che crea una stanza virtuale</b> può accedere ai contenuti del sito, scaricare i materiali, può caricare i materiali, può avviare una videoconferenza </li>
    <li><b>Utente admin</b> può effettuare tutte le operazioni sui materiali e sugli utenti e gestire i permessi </li>
  </ul>

  <h3 class="text-center">Utente anonimo</h3>

  <p>
    Un qualsiasi utente che naviga sul sito fare.polito.it, un utente anonimo può navigare sul portale
    FARE effettuando ricerche, può esplorare tutto il materiale
    didattico caricato e può scaricare qualsiasi file pubblico
    (<a href="{{ url_for('file_management.retrieve_guide_search') }}">Guida alla ricerca e al download</a>)
  </p>

  <h3 class="text-center">Utente iscritto</h3>

  <p>
    Un utente che ha effettuato l’accesso al portale FARE, un utente iscritto può compiere tutte le azioni
    di un utente anonimo e in più può caricare del materiale didattico nell'apposita sezione
    (<a href="{{ url_for('file_management.retrieve_guide_upload') }}">Guida per caricare un file</a>).
    <br>
    I file caricati possono essere cancellati dall'utente che li ha caricati in qualsiasi momento visitando la pagina personale
    del file e premendo il bottone
    <button class="btn btn-danger">
      <i class="fa fa-trash" aria-hidden="true"></i>
      Rimuovi
    </button>
    oppure possono essere rimossi dagli utenti admin
  </p>

  <h3 class="text-center">Utente staff</h3>

  <p>
    Un utente staff può compiere tutte le azioni di un utente iscritto e in più ha il compito di revisionare
    il materiare caricato dagli utenti. Per revisionare i files bisogna selezionare nel menù in alto a destra come mostrato sotto
    per aprire la tendina con le opzioni e cliccare alla voce <b>Revisione contenuti</b> con questo simbolo -> <i class="fa fa-eye fa-fw"></i>.
  </p>

  <img class="guide-image-small" src="{{ url_for('static', filename='images/staff_menu.png') }}" alt="Menu_staff"/>

  <p>
    Se sono presenti files non ancora revisionati, comparirà una lista di files da revisionare come nell'immagine seguente:
  </p>

  <img class="guide-image-medium" src="{{ url_for('static', filename='images/revision_record_list.png') }}" alt="Revision_list"/>

  <p>
    Se si clicca nel titolo, in questo caso <b>La storia dell'informatica</b>, si accederà alle informazioni del contenuto selezionato
  </p>

  <img class="guide-image-medium" src="{{ url_for('static', filename='images/revision_record_page.png') }}" alt="Revision_page"/>

  <p>
    In questa pagina è possibile scaricare il file cliccando il bottone
    <button class="btn btn-primary">
      <i class="fa fa-download" aria-hidden="true"></i> Download
    </button>
    per controllarne il contenuto. Se il materiale viene ritenuto idoneo
    lo si può pubblicare cliccando il bottone
    <button class="btn btn-success">
      <i class="fa fa-check" aria-hidden="true"></i>
      Pubblica
    </button>
    . In caso contrario si può cancellare il file cliccando il bottone
    <button class="btn btn-danger">
      <i class="fa fa-trash" aria-hidden="true"></i>
      Rimuovi
    </button>
  </p>

  <p>
    Un utente <b>staff</b> può concedere a un altro utente iscritto al portale FARE il ruolo di <b>staff</b>.
    Basta cliccare nel menù in alto a destra alla
    voce <b>Concedi permessi</b> con il simbolo -> <i class="fa fa-users" aria-hidden="true"></i> ed accedere alla pagina
    per la concessione dei permessi come riportato in figura:
  </p>

  <img class="guide-image-large" src="{{ url_for('static', filename='images/grant_staff.png') }}" alt="Grant_staff"/>

  <p>
    Bisogna inserire la mail dell'utente a cui si vuol dare il permesso di <b>staff</b> e cliccare il pulsante
    <button class="btn btn-warning">Abilita</button>
  </p>

  <h3 class="text-center">Utente che crea una stanza virtuale</h3>

  <p>
    Gli utenti con questo permesso potranno creare una stanza virtuale. Per creare una stanza virtuale basta
    cliccare nel menù in alto a destra come mostrato nella figura sotto per aprire la tendina con le opzioni
  </p>

  <img class="guide-image-small" src="{{ url_for('static', filename='images/create_virtual_room_menu.png') }}" alt="Menu_room_creator"/>

  <p>
    Successivamente bisogna cliccare alla voce <b>Crea stanza</b> con questo simbolo -> <i class="fa fa-video-camera fa-fw"></i>.
    Così facendo comparirà la pagina per creare una stanza virtuale come quella mostrata nella figura sotto
  </p>

  <img class="guide-image-large" src="{{ url_for('static', filename='images/create_virtual_room.png') }}" alt="Create_virtual_room"/>

  <p>
    Per creare una stanza virtuale bisogna inserire negli appositi campi l'id della stanza, che deve essere univoco, la password e
    il nome e cognome di chi crea la stanza. Una volta cliccato sul pulsante
    <button class="btn btn-warning">
      <i class="fa fa-video-camera" aria-hidden="true"></i>
      Crea
    </button>
    si entrerà automaticamente nella stanza virtuale.
  </p>

</div>

{{ webpack['guide.css'] }}

{% endblock page_body %}

fare/file_management/templates/file_management/guide_search.html
{%- extends config.BASE_TEMPLATE %}

{% block page_body %}

<h1 class="text-center">Guida alla ricerca del materiale su FARE</h1>

<div class="container">

<p>
  E' possibile effettuare ricerche per parole chiave.
  Una parola chiave potrebbe essere il titolo con cui è stato caricato il materiale,
  il nome di un autore (esempio: Mezzalama), il nome di una disciplina (esempio Informatica),
  un argomento, l'ordine di scuola (esempio Scuola Secondaria di secondo grado) e infine la licenza
  Creative Commons. E’ possibile effettuare una ricerca per le seguenti discipline:
</p>

    <table class="table table-bordered table-striped">
      <tbody>
      {% for sub in subjects['subject'] %}
        {% if loop.index0 % 3 == 0 %}
        <tr>
        {% endif %}
          <td>
            {{ sub }}
          </td>
        {% if loop.index0 % 3 == 2 or loop.last %}
          </tr>
        {% endif %}
      {% endfor %}
      </tbody>
    </table>

<p>
  le classi di insegnamento sono:
</p>

    <table class="table table-bordered table-striped">
      <tbody>
      {% for level in education_levels['educationLevel'] %}
        {% if loop.index0 % 3 == 0 %}
        <tr>
        {% endif %}
          <td>
            {{ level }}
          </td>
        {% if loop.index0 % 3 == 2 or loop.last %}
          </tr>
        {% endif %}
      {% endfor %}
      </tbody>
    </table>

<p>
  Di seguito è mostrato il risultato di una ricerca
</p>

<img class="guide-image-large" src="{{ url_for('static', filename='images/example_record_search.png') }}" alt="Research_result"/>

<p>
  Selezionando il titolo di uno dei risultati si potranno visualizzare tutti i dettagli dell’argomento:
  è indicata la classe di insegnamento, la disciplina, l’argomento, gli autori del materiale, sono indicate
  le informazioni relative alla licenza Creative Commons con cui è stato caricato il file
  (per maggiori informazioni sulle licenze Creative Commons cliccare
  <a href="https://creativecommons.it/chapterIT/">qui</a> <i class="fa fa-external-link" aria-hidden="true"></i> ).
  Infine, è possibile effettuare il download cliccando sul pulsante
  <button class="btn btn-primary">
    <i class="fa fa-download" aria-hidden="true"></i> Download
  </button>
</p>

<img class="guide-image-large" src="{{ url_for('static', filename='images/example_record_page.png') }}" alt="Record_page"/>

</div>

{{ webpack['guide.css'] }}

{% endblock page_body %}

fare/file_management/templates/file_management/guide_upload.html
{%- extends config.BASE_TEMPLATE %}

{% block page_body %}

<div class="container">

<h1 class="text-center">Guida al caricamento dei files su FARE</h1>

<p>
  Su FARE tutti gli utenti registrati possono caricare del materiale didattico, basta cliccare sul menù in alto come mostrato sotto
</p>

<img class="guide-image-small" src="{{ url_for('static', filename='images/menu_options.png') }}" alt="Menu"/>

<p>
  Dopo che il menù a tendina si sarà aperto selezionare la voce <b>Carica file</b> con il simbolo <i class="fa fa-file-text fa-fw"></i>
</p>

<img class="guide-image-small" src="{{ url_for('static', filename='images/upload_file.png') }}" alt="Upload"/>

<p>
  A questo punto sarà possibile inserire i dati relativi al materiale didattico e il file
  come riportato nell'immagine seguente
</p>

<img class="guide-image-medium" src="{{ url_for('static', filename='images/record_form.png') }}" alt="Form"/>

<p>
  Compilati tutti i campi: titolo, autori, ordine di scuola, disciplina, argomento, una descrizione del contenuto del materiale
  che si sta caricando, la licenza creative common con cui caricare il materiale (
  per saperne di più sulle licenze Creative Commons clicca
  <a href="https://creativecommons.org/licenses/?lang=it">qui</a><i class="fa fa-external-link" aria-hidden="true"></i>
  ) e infine selezionare dal tuo computer il file da caricare e cliccare sul pulsante
  <button type="submit" class="btn btn-default">Crea</button>.
  Se l'operazione è avvenuta con successo comparirà la schermata seguente
</p>

<img class="guide-image-large" src="{{ url_for('static', filename='images/record_upload_after.png') }}" alt="After_upload"/>

<p>
  Un utente iscritto a FARE che ha caricato dei documenti può vedere il loro stato, quali sono stati revisionati e quindi resi pubblici,
  e quali sono ancora in fase di revisione. Per verificarlo effettuare l'accesso e cliccare nel menù come mostrato nell'immagine di seguito
</p>

<img class="guide-image-small" src="{{ url_for('static', filename='images/menu_options.png') }}" alt="Menu"/>

<p>
  Per verificare lo stato dei file cliccare alla voce
  <b>Stato files</b> con il simbolo <i class="fa fa-check-circle" aria-hidden="true"></i> , come mostrato nell'immagine di seguito
</p>

<img class="guide-image-small" src="{{ url_for('static', filename='images/status_file.png') }}" alt="Status"/>

<p>
  Saranno allora visibili tutti i files caricati con l'account con il quale è stato effettuato
  l'accesso, nell’immagine di seguito è riportato un esempio
</p>

<img class="guide-image-large" src="{{ url_for('static', filename='images/status_records.png') }}" alt="Status"/>

<p>
  <b>NOTA:</b> se accanto al file compare la scritta
  <span class="label label-danger">da revisionare</span>
  , vuol dire che il file deve ancora essere revisionato per poter essere reso pubblico.
  Se invece compare la scritta
  <span class="label label-info">pubblicato</span>
  allora il file è stato reso pubblico e può essere scaricato da tutti.
</p>


</div>

{{ webpack['guide.css'] }}

{% endblock page_body %}

fare/file_management/templates/file_management/info_create.html
{%- extends config.BASE_TEMPLATE %}

{% block page_body %}

{%- block page_header %}
{%- endblock page_header %}

<header>
  {%- block navbar %}
  <nav class="navbar navbar-default navbar-static-top">
    <div class="container">
      {%- block navbar_header %}
      <div class="navbar-header">
        {%- block brand %}
        {%- if config.THEME_LOGO %}
          <a href="/"><img class="navbar-brand" src="{{ url_for('static', filename=config.THEME_LOGO)}}" alt="{{_(config.THEME_SITENAME)}}" /></a>
        {%- else %}
          <a class="navbar-brand" href="/">{{_(config.THEME_SITENAME)}}</a>
        {%- endif %}
        {%- endblock %}
      </div>
      {%- endblock navbar_header %}
    </div>
  </nav>
  {%- endblock navbar %}
</header>

<div class="container">
  <div class="element-block">

    <h1 class="text-center">
      Carica il materiale
    </h1>

    <br>

    {% if not current_user.is_authenticated %}

    <div class="row">

      <div class="col-sm-3">
      </div>

      <div class="col-sm-6 text-center">

        <div class="row">
          <div class="col-sm-12">
            <div class="alert alert-info" role="alert">
              <h4>
                Per accedere ai servizi di FARE occorre in primo luogo "registrarsi" ossia trasmettere
                a FARE il proprio indirizzo di posta elettronica e una proposta di password.
                Questa registrazione si ottiene cliccando sul pulsante  chiamato "Registrati".
                <br>
                Se ti sei già registrato oggi o in qualunque altro momento, non serve una nuova registrazione.
                <br>
                Se sei già registrato puoi procedere all'installazione di un nuovo oggetto didattico premendo
                il tasto chiamato "Accedi".
                <br>
                Il nuovo oggetto sarà sottoposto all'attenzione dell'amministrazione del sistema. Solo dopo
                l'approvazione dell'amministrazione quell'oggetto sarà caricato nell'archivio di FARE
              </h4>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-sm-12">
            <a href="{{url_for_security('login', next=request.path)}}" class="btn btn-default btn-lg">
              <i class="fa fa-sign-in"></i> Accedi
            </a>
            <a href="{{url_for_security('register')}}" type="submit" class="btn btn-default btn-warning btn-lg">
              <i class="fa fa-edit"></i> Registrati
            </a>
          </div>
        </div>

      </div>

      <div class="col-sm-3">
      </div>

    </div>

    {% endif %}

  </div>
</div>

{% endblock page_body %}

fare/file_management/templates/file_management/search_page.html
{%- extends config.BASE_TEMPLATE %}

{%- block page_header %}
{%- include 'fare/header_frontpage.html' %}
{%- endblock page_header %}

{% block page_body %}
<div class="body-image">
  <div class="row frontpage-search">
    <div class="col-md-12 search-block-background">
      <h1 class="text-center">
          Cerca per autore, materia, livello di insegnamento, parola chiave
      </h1>
      <h3 class="text-center">
        per maggiori informazioni sulla ricerca clicca
        <a href="{{ url_for('file_management.retrieve_guide_search') }}">qui</a>
      </h3>
      <form action="/search">
        <div class="form-group">
          <div class="input-group">
            <input type="text" name="q" class="input-lg form-control" placeholder="Type and press enter to search">
            <div class="input-group-btn">
              <button type="submit" class="btn btn-lg btn-default"><i class="fa fa-search"></i></button>
            </div>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>

{{ webpack['fare-search-page.css'] }}

{% endblock page_body %}