fare/grant_roles/forms.py
"""grant_roles form module."""

from __future__ import absolute_import, print_function

from flask_wtf import FlaskForm
from wtforms import validators
from wtforms.fields.html5 import EmailField


class RolesForm(FlaskForm):
    """grant_roles form."""

    email = EmailField(
        'Email', [validators.DataRequired(), validators.Email()]
    )

fare/grant_roles/__init__.py
"""grant_roles module."""

fare/grant_roles/views.py
"""Views for grant_roles permission to other users."""

from __future__ import absolute_import, print_function

from flask import Blueprint, redirect, render_template, url_for
from flask_babelex import gettext as _
from flask_login import login_required
from flask_menu import register_menu
from flask_security import current_user, roles_accepted

from .api import grant_room_creator_permission, grant_staff_permission
from .forms import RolesForm

# define a new Flask Blueprint that is register under
# the url path /grant_roles
blueprint = Blueprint(
    'grant_roles',
    __name__,
    url_prefix='/grant_roles',
    template_folder='templates',
    static_folder='static',
)


@blueprint.route('/grant', methods=('GET',))
@login_required
@roles_accepted('admin', 'staff')
@register_menu(blueprint, 'settings.grant',
               _('%(icon)s Concedi permessi',
                   icon='<i class="fa fa-users fa-fw"></i>'),
               order=7,
               visible_when=lambda: bool(current_user.has_role('admin') or
                                         current_user.has_role('staff')
                                         ) is not False
               )
def grant():
    """The grant view."""
    form = RolesForm()
    return render_template('grant_roles/grant.html', form=form)


@blueprint.route('/grant_staff', methods=('GET', 'POST'))
@login_required
@roles_accepted('admin', 'staff')
def grant_staff():
    """The grant staff view."""
    form = RolesForm()

    # if the form is submitted and valid
    if form.validate_on_submit():
        # store the form information
        user = form.email.data

        status = grant_staff_permission(user)

        # check if the user exist
        if status == 404:
            return redirect(url_for('grant_roles.user_not_found'))
        # if successfull print it in the terminal with green color
        if status == 409:
            # Cannot add role to user
            return redirect(url_for('grant_roles.cannot_add_role'))

        # redirect to the success page
        return redirect(url_for('grant_roles.success'))
    return redirect(url_for('grant_roles.grant'))


@blueprint.route('/grant_room_creator', methods=('GET', 'POST'))
@login_required
@roles_accepted('admin')
def grant_room_creator():
    """The grant roomCreator view."""
    form = RolesForm()

    # if the form is submitted and valid
    if form.validate_on_submit():
        # store the form information
        user = form.email.data

        status = grant_room_creator_permission(user)

        # check if the user exist
        if status == 404:
            return redirect(url_for('grant_roles.user_not_found'))
        # if successfull print it in the terminal with green color
        if status == 409:
            # Cannot add role to user
            return redirect(url_for('grant_roles.cannot_add_role'))

        # redirect to the success page
        return redirect(url_for('grant_roles.success'))
    return redirect(url_for('grant_roles.grant'))


@blueprint.route("/success")
@login_required
def success():
    """The success view."""
    return render_template('grant_roles/success.html')


@blueprint.route("/cannot_add_role")
@login_required
def cannot_add_role():
    """The cannot add role view."""
    return render_template('grant_roles/cannot_add_role.html'), 409


@blueprint.route("/user_not_found")
@login_required
def user_not_found():
    """The user not found view."""
    return render_template('grant_roles/user_not_found.html'), 404

fare/grant_roles/templates/grant_roles/cannot_add_role.html
{%- extends config.BASE_TEMPLATE %}

{% block page_body %}
  <div class="container">
    <div class="element-block">
      <div class="row">
        <div class="col-md-12">
          <div class="alert alert-danger">
            <b>Impossibile aggiungere il ruolo all'utente selezionato.</b>
          </div>
          <a href="{{ url_for('grant_roles.grant') }}" class="btn btn-warning">Torna alla pagina dei permessi</a>
        </div>
      </div>
    </div>
  </div>
{% endblock page_body %}

fare/grant_roles/templates/grant_roles/grant.html
{%- extends config.BASE_TEMPLATE %}

{% macro errors(field) %}
  {% if field.errors %}
  <span class="help-block">
    <ul class=errors>
    {% for error in field.errors %}
      <li>{{ error }}</li>
    {% endfor %}
    </ul>
  {% endif %}
  </span>
{% endmacro %}

{% block page_body %}
  <div class="container">

    <div class="element-block">

      <div class="row">

        <div class="col-sm-2 text-center">
          <i class="fa fa-users fa-5x aria-hidden='true' create-file-icon"></i>
        </div>

        <div class="col-sm-8 text-center">

          <h2>Fai diventare un membro <b>Staff</b></h2>

          <br>

          <p>
            Dai la possibilità ad altri utenti di FARE di
            revisionare contenuti che aspettano di essere
            pubblicati sulla piattaforma, inserisci la mail
            nel box e premi il tasto <b>'Abilita'</b>
          </p>

        </div>

        <div class="col-sm-2 text-center">
          <i class="fa fa-users fa-5x aria-hidden='true' create-file-icon"></i>
        </div>

      </div>

      <br><br>

      <div class="row">

        <div class="col-sm-3"></div>

        <div class="col-sm-6 well">
          <form action="{{ url_for('grant_roles.grant_staff') }}" method="POST">
            <div class="form-group {{ 'has-error' if form.email.errors }}">
              <label for="email">{{ form.email.label }}</label>
              {{ form.email(class_="form-control")|safe }}
              {{ errors(form.email) }}
            </div>
            {{ form.csrf_token }}
            {{ errors(form.csrf_token) }}
            <button type="submit" class="btn btn-warning">Abilita</button>
          </form>
        </div>

        <div class="col-sm-3"></div>

      </div>

    </div>

    <br><br>

    {% if current_user.has_role('admin')%}

    <div class="element-block">

      <div class="row">

        <div class="col-sm-2 text-center">
          <i class="fa fa-video-camera fa-5x aria-hidden='true' create-file-icon"></i>
        </div>

        <div class="col-sm-8 text-center">
          <h2>Permesso per creare una stanza virtuale</h2>

          <br>

          <p>
            Dai la possibilità ad altri utenti di FARE di
            creare una stanza virtuale nella quale svolgere
            le sue lezioni, inserisci la mail nel box e
            premi il tasto <b>'Abilita'</b>
          </p>

        </div>

        <div class="col-sm-2 text-center">
          <i class="fa fa-video-camera fa-5x aria-hidden='true' create-file-icon"></i>
        </div>

      </div>

      <br><br>

      <div class="row">

        <div class="col-sm-3"></div>

        <div class="col-md-6 well">
          <form action="{{ url_for('grant_roles.grant_room_creator') }}" method="POST">
            <div class="form-group {{ 'has-error' if form.email.errors }}">
              <label for="email">{{ form.email.label }}</label>
              {{ form.email(class_="form-control")|safe }}
              {{ errors(form.email) }}
            </div>
            {{ form.csrf_token }}
            {{ errors(form.csrf_token) }}
            <button type="submit" class="btn btn-warning">Abilita</button>
          </form>
        </div>

        <div class="col-sm-3"></div>

      </div>

    </div>

    {% endif %}

  </div>

{% endblock page_body %}

fare/grant_roles/templates/grant_roles/success.html
{%- extends config.BASE_TEMPLATE %}

{% block page_body %}
  <div class="container">
    <div class="element-block">
      <div class="row">
        <div class="col-md-12">
          <div class="alert alert-success">
            <b>Utente abilitato con successo!</b>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock page_body %}

fare/grant_roles/templates/grant_roles/user_not_found.html
{%- extends config.BASE_TEMPLATE %}

{% block page_body %}
  <div class="container">
    <div class="element-block">
      <div class="row">
        <div class="col-md-12">
          <div class="alert alert-danger">
            <b>Utente non trovato.</b>
          </div>
          <a href="{{ url_for('grant_roles.grant') }}" class="btn btn-warning">Torna alla pagina dei permessi</a>
        </div>
      </div>
    </div>
  </div>
{% endblock page_body %}