fare/conference/forms.py
"""conference form module."""

from __future__ import absolute_import, print_function

from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileRequired
from wtforms import PasswordField, StringField, validators


class RoomForm(FlaskForm):
    """conference form."""

    roomId = StringField(
        'Room id', [validators.DataRequired(),
                    validators.Regexp(r'^[\w.@+-]+$',
                    message="Il campo non può contenere spazi")]
    )

    password = PasswordField(
        'Room password', [validators.DataRequired()]
    )

    username = StringField(
        'Name of the user', [validators.DataRequired()]
    )

fare/conference/__init__.py
"""conference module."""

fare/conference/views.py
"""Views for create virtual rooms for conferences."""

from __future__ import absolute_import, print_function

import json
import os
import secrets

from bigbluebutton_api_python import BigBlueButton
from bigbluebutton_api_python.exception.bbbexception import BBBException
from dotenv import load_dotenv
from flask import Blueprint, abort, current_app, redirect, render_template, \
    request, url_for
from flask_babelex import gettext as _
from flask_login import login_required
from flask_menu import register_menu
from flask_security import current_user, roles_accepted

from .forms import RoomForm

# Loading dotenv
load_dotenv()

#: Big Blue Button server secret and url
BBB_SERVER_SECRET = os.getenv('BBB_SERVER_SECRET')
BBB_SERVER_URL = os.getenv('BBB_SERVER_URL')

# define a new Flask Blueprint that is register
# under the url path /conference
blueprint = Blueprint(
    'conference',
    __name__,
    url_prefix='/conference',
    template_folder='templates',
    static_folder='static',
)


@blueprint.route('/create_room', methods=('GET', 'POST'))
@register_menu(blueprint, 'settings.createroom',
               _('%(icon)s Crea videoconferenza',
                 icon='<i class="fa fa-video-camera fa-fw"></i>'
                 ),
               order=7,
               visible_when=lambda: bool(current_user.has_role('admin') or
                                         current_user.has_role('roomCreator')
                                         ) is not False
               )
def create_room():
    """View to let user create a virtual room."""
    if current_user.is_authenticated:
        if ('admin' in current_user.roles) or \
           ('roomCreator' in current_user.roles):
            form = RoomForm()

            # if the form is submitted and valid
            if form.validate_on_submit():
                roomId = form.roomId.data.strip()
                password = form.password.data
                username = form.username.data.strip().replace(" ", "_")
                modPassword = secrets.token_hex(16)

                b = BigBlueButton(BBB_SERVER_URL, BBB_SERVER_SECRET)

                # params
                dict = {
                    'name': username,
                    'attendeePW': password,
                    'moderatorPW': modPassword,
                    'record': True
                }

                if os.getenv('CURRENT_HOST'):
                    dict['logoutURL'] = os.getenv('CURRENT_HOST')

                try:
                    # use create meeting
                    b.create_meeting(roomId, params=dict)
                except BBBException:
                    return render_template(
                        'conference/create_conference.html',
                        form=form, existingId=True)

                # get room url
                room_url = b.get_join_meeting_url(username,
                                                  roomId,
                                                  modPassword)

                # redirect to the created room
                return redirect(room_url)

            return render_template('conference/create_conference.html',
                                   form=form)
        else:
            return render_template('conference/info_create.html')
    else:
        return render_template('conference/info_create.html')


@blueprint.route('/join_room', methods=('GET', 'POST'))
def join_room():
    """View to let user join a virtual room."""
    form = RoomForm()

    # if the form is submitted and valid
    if form.validate_on_submit():
        roomId = form.roomId.data.strip()
        password = form.password.data
        username = form.username.data.strip().replace(" ", "_")

        b = BigBlueButton(BBB_SERVER_URL, BBB_SERVER_SECRET)

        r = b.is_meeting_running(roomId)

        active_room = json.loads(r['xml']['running'].lower())

        # check if the meeting exists
        if not active_room:
            return render_template('conference/join_conference.html',
                                   form=form, existingId=True)
        else:
            # get room url
            room_url = b.get_join_meeting_url(username, roomId, password)

            # redirect to the room
            return redirect(room_url)

    return render_template('conference/join_conference.html', form=form)

fare/conference/templates/conference/create_conference.html
{%- extends config.BASE_TEMPLATE %}

{% macro errors(field) %}
  {% if field.errors %}
  <span class="help-block">
    <ul class=errors>
    {% for error in field.errors %}
      <li>{{ error }}</li>
    {% endfor %}
    </ul>
  {% endif %}
  </span>
{% endmacro %}

{% block page_body %}
  <div class="container">
    <div class="element-block">

      <div class="row">
        {% if existingId is defined %}
          <div class="alert alert-danger alert-dismissible text-center" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            Id esistente, scegline uno più specifico
          </div>
        {% endif %}
      </div>

      <div class="row">

        <div class="col-md-12">

          <div class="row">
            <div class="col-md-12">
            <h1 class="text-center">Attiva una videoconferenza/videolezione</h1><br>
            </div>
          </div>

          <div class="row">

            <div class="col-md-3"></div>

            <div class="col-md-6 well">

              <form action="{{ url_for('conference.create_room') }}" method="POST" enctype="multipart/form-data">

                  <div class="form-group {{ 'has-error' if form.roomId.errors }}">
                    <label for="roomId">Id della videoconferenza/videolezione (deve essere univoco)</label>
                   <br>
                    <small>esempio: materia-sezione-docente</small>
                    {{ form.roomId(class_="form-control")|safe }}
                    {{ errors(form.roomId) }}
                  </div>

                  <div class="form-group {{ 'has-error' if form.password.errors }}">
                    <label for="password">Password videoconferenza/videolezione - almeno 4 caratteri </label>
                    {{ form.password(class_="form-control")|safe }}
                    {{ errors(form.password) }}
                  </div>

                  <div class="form-group {{ 'has-error' if form.username.errors }}">
                    <label for="username">Cognome e nome di chi crea la videoconferenza/videolezione</label>
                    {{ form.username(class_="form-control")|safe }}
                    {{ errors(form.username) }}
                  </div>

                  {{ form.csrf_token }}
                  {{ errors(form.csrf_token) }}
                  <div class="text-center">
                  <button type="submit" class="btn btn-warning">
                    <i class="fa fa-video-camera" aria-hidden="true"></i>
                    Attiva
                  </button>
                  </div>

              </form>

            </div>

            <div class="col-md-3"></div>

          </div>

        </div>

      </div>

    </div>
  </div>

{% endblock page_body %}

fare/conference/templates/conference/info_create.html
{%- extends config.BASE_TEMPLATE %}

{% block page_body %}

{%- block page_header %}
{%- endblock page_header %}

<header>
  {%- block navbar %}
  <nav class="navbar navbar-default navbar-static-top">
    <div class="container">
      {%- block navbar_header %}
      <div class="navbar-header">
        {%- block brand %}
        {%- if config.THEME_LOGO %}
          <a href="/"><img class="navbar-brand" src="{{ url_for('static', filename=config.THEME_LOGO)}}" alt="{{_(config.THEME_SITENAME)}}" /></a>
        {%- else %}
          <a class="navbar-brand" href="/">{{_(config.THEME_SITENAME)}}</a>
        {%- endif %}
        {%- endblock %}
      </div>
      {%- endblock navbar_header %}
    </div>
  </nav>
  {%- endblock navbar %}
</header>

<div class="container">
  <div class="element-block">

    <h1 class="text-center">
      Crea una videoconferenza/videolezione
    </h1>

    <br>

    {% if current_user.is_authenticated %}

      {% if not current_user.has_role('roomCreator') or not current_user.has_role('admin') %}

        <div class="row">
          <div class="col-sm-12 text-center">
            <i class="fa fa-ban fa-5x aria-hidden='true' create-file-icon"></i>
          </div>
        </div>

        <br><br>

        <div class="row">

          <div class="col-sm-3">
          </div>

          <div class="col-sm-6 text-center">
            <div class="alert alert-danger" role="alert">
              <h4>
                Non hai il permesso per creare una videoconferenza/videolezione
                invia una mail all'indirizzo
                <b>{{ config.SUPPORT_EMAIL }}</b>
                per contattarci e richiederlo
              </h4>
            </div>
          </div>

          <div class="col-sm-3">
          </div>

        </div>

      {% endif %}

    {% else %}

      <div class="row">

        <div class="col-sm-3"></div>

        <div class="col-sm-6 text-center">

          <div class="row">
            <div class="col-sm-12">
              <div class="alert alert-info" role="alert">
                <h4>
                  Per accedere ai servizi di FARE occorre in primo luogo "registrarsi" ossia trasmettere
                  a FARE il proprio indirizzo di posta elettronica e una proposta di password.
                  Questa registrazione si ottiene cliccando sul pulsante  chiamato "Registrati".
                  <br>
                  Se ti sei già registrato oggi o in qualunque altro momento, non serve una nuova registrazione.
                  <br>
                  Se sei già registrato puoi procedere all'attivazione di una video lezione o videoconferenza
                  premendo il pulsante chiamato "Accedi".
                </h4>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-sm-12">
              <a href="{{url_for_security('login', next=request.path)}}" class="btn btn-default btn-lg">
                <i class="fa fa-sign-in"></i> Accedi
              </a>
              <a href="{{url_for_security('register')}}" type="submit" class="btn btn-default btn-warning btn-lg">
                <i class="fa fa-edit"></i> Registrati
              </a>
            </div>
          </div>

        </div>

        <div class="col-sm-3"></div>

      </div>

    {% endif %}

  </div>
</div>

{% endblock page_body %}

fare/conference/templates/conference/join_conference.html
{%- extends config.BASE_TEMPLATE %}

{% macro errors(field) %}
  {% if field.errors %}
  <span class="help-block">
    <ul class=errors>
    {% for error in field.errors %}
      <li>{{ error }}</li>
    {% endfor %}
    </ul>
  {% endif %}
  </span>
{% endmacro %}

{% block page_body %}
  <div class="container">
    <div class="element-block">

      <div class="row">
        {% if existingId is defined %}
          <div class="alert alert-danger alert-dismissible text-center" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            Non esiste una videoconferenza/videolezione con questo ID
          </div>
        {% endif %}
      </div>

      <div class="row">

        <div class="col-md-12">

          <div class="row">
            <div class="col-md-12">
              <h1 class="text-center">Partecipa a una videoconferenza/videolezione</h1><br>
              <h3 class="text-center">
                Per partecipare ad una videoconferenza/videolezione <br> bisogna conoscerne il nome e la password
              </h3>
            </div>
          </div>

          <div class="row">

            <div class="col-md-3"></div>

            <div class="col-md-6 well">

              <form action="{{ url_for('conference.join_room') }}" method="POST" enctype="multipart/form-data">

                  <div class="form-group {{ 'has-error' if form.roomId.errors }}">
                    <label for="roomId">Nome della videoconferenza/videolezione alla quale vuoi partecipare</label>
                    {{ form.roomId(class_="form-control")|safe }}
                    {{ errors(form.roomId) }}
                  </div>

                  <div class="form-group {{ 'has-error' if form.password.errors }}">
                    <label for="password">Password della videoconferenza/videolezione</label>
                    {{ form.password(class_="form-control")|safe }}
                    {{ errors(form.password) }}
                  </div>

                  <div class="form-group {{ 'has-error' if form.username.errors }}">
                    <label for="username">Cognome e nome con i quali partecipare alla videoconferenza/videolezione</label>
                    {{ form.username(class_="form-control")|safe }}
                    {{ errors(form.username) }}
                  </div>

                  {{ form.csrf_token }}
                  {{ errors(form.csrf_token) }}
                  <div class="text-center">
                  <button type="submit" class="btn btn-warning">
                    <i class="fa fa-video-camera" aria-hidden="true"></i>
                    Partecipa
                  </button>
                  </div>

              </form>

            </div>

            <div class="col-md-3"></div>

          </div>

        </div>

      </div>

    </div>
  </div>

{% endblock page_body %}